name: optdesk
description: A new Flutter package project.
version: 0.0.1


environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
  flutter_platform_widgets:
  otp_text_field:
  auto_size_text:
  table_calendar:
  flutter_linkify:
  file_picker:
  dio:
  flutter_easyloading:
  get:

  i2iutils:
    # git:
    # url: https://github.com/i2isoftwares/i2iutils.git
    path: ../../i2iutils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


